### ISSUE TITLE
Move build system from make to more modern cmake system

### ISSUE THREAD

**Issue by BenjaminSoelberg** [BenjaminSoelberg/openchronos-ng-elf#10]

**Comment by pretyman** [comment]
I guess https://github.com/BenjaminSoelberg/openchronos-ng-elf/pull/22 fits here.

I completely rewrote the current CMake scripts as they weren't working for me on CMake 3.6 and 3.7.

There are still features to be added to completely substitute the current make targets. 

I will implement them as necessity strikes in.

**Comment by BenjaminSoelberg** [comment]
Sounds like a great start!
The initial cmake file was a trial and error for me.
How about adding a "missing features" list to either this issue or creating a issue group to track the progress ?

**Comment by pretyman** [comment]
Sorry for taking long to answer, got busy with real life things.

The idea of missing features is good and all, but it was easier for me to bang all the features in one go, since there weren't many. It is in https://github.com/BenjaminSoelberg/openchronos-ng-elf/pull/31

I also added a target `usb-debug` for starting the gdb bridge of mspdebug. Working good with CLion IDE.

**Comment by BenjaminSoelberg** [comment]
Note from pretyman:
Made the following changes: https://github.com/BenjaminSoelberg/openchronos-ng-elf/pull/35
CMake target radio-install works with this change, but contrib/ChronosTool.py is failing for me.
