### ISSUE TITLE
RF examples / example module?

### ISSUE THREAD

**Issue by mupfdev** [BenjaminSoelberg/openchronos-ng-elf#59]
Hello,
first of all: thanks for maintaining this project. It really helped me to get into Ez430 Chronos development.

What I couldn't figure out yet is how to access the RF functions (which was the main reason why I was so interested in this watch/mcu). Could you add by any chance an example module to demonstrate how to communicate between the watch and USB wireless adapter (e.g. using minicom) and/or between two watches? Or could you add functions to make this feature more generic/more easily accessible?

Greetings,
Michael

**Comment by cynum** [comment]
Hi Michael and happy easter to all,

I am quite new to the project and the chronos watch myself. The project is as far as I can tell not very active anymore, but I am working on some projects with the chronos and openchronos and will try to contribute to this project whenever possible.

Using RF for some kind of communications is also a goal of mine, for the moment mainly to transmit the accel data. So far I can tell you that the communication of data from the watch to the PC with the RF usb dongle works using the original Recovery software in the Acc mode. On the computer I am using the python scripts that are available in the contrib folder. In this combination it is possible to receive data from the watch to the computer.

I did not manage to successfully rx data using the ChronosTool.py

As far as I can tell openchronos does not have the necessary software modules for transmission of data to the USB dongle, yet. Since I want to use that functionality also, I might try to write it using the original software sources as basis sooner or later. If you care to code something already in the meantime please let me know :-).

Ah and, what is REALLY awful is that the battery needs to be almost 100% full, otherwise no communication works reliably. I strongly suggest to hook the watch up to an external power source instead of a battery while developing...

Best wishes,
Alexander

**Comment by mupfdev** [comment]
Hey Alexander,
it's good to hear that someone is still actively working on projects based on openchronos-ng. Are you working on something in particular?

For my project idea I would be interested to figure out a way to RX data using the watch. I also have a RFBee-module from Seeedstudio in stock. Well, maybe we can huddle together if the time permits it. :+1:

About the external power source: any convenient way to do so?

**Comment by BenjaminSoelberg** [comment]
Welcome to both of you!
The RF stack is indeed working but uses a lot of power. And wireless update seems to quit working below 88%...strange...

Anyway low level radio functions is available in radio.c.
Don't know the state of it.
To be hones, this guy knows a lot about it:
https://github.com/quoraquestions
Im trying to get him back on board again :-)

**Comment by BenjaminSoelberg** [comment]
Oh and I will close this issue and direct you both to use the SLACK channel.

**Comment by BenjaminSoelberg** [comment]
slack link : https://join.slack.com/t/openchronos/shared_invite/enQtMzQzMjE2NzQzNzYyLTU5NDhiYWFjZjE3NzdlMWUxMTM3OGJiYzg4ODYyMmUzNjg5ZThhZTI2ODhkMDZiZmM3NmJiNjEwYTA5M2IzZmM
